[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.19"
verbosity = 3
block_timestamp = 0
block_gas_limit = 30000000
remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/"
]

[rpc_endpoints]
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api/", chain = 421614 }

[fuzz]
runs = 1024
# max_test_rejects = 65536
# seed = '0x3e8'
# dictionary_weight = 40
# include_storage = true
# include_push_bytes = true

[fmt]
single_line_statement_blocks = "single"
override_spacing = false
line_length = 120
wrap_comments = false
number_underscore = "preserve"
tab_width = 4
bracket_spacing = false
quote_style = "double"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
